lib, panic: don't call do_reset in SPL (debug).
Several omap boards won't build when DEBUG is defined, SPL build error:
"vsprintf.c:791: undefined reference to `do_reset'", since SPL has no
commands. Therefore don't call do_reset in SPL. SPL panic will end in an
endless loop or call hang if CONFIG_PANIC_HANG is defined.

cc: Tom Rini <trini@ti.com>
Signed-off-by: Jeroen Hofstee <jhofstee@victronenergy.com>